const actionTypes = {
    INIT_LOAD_DATA: 'INIT_LOAD_DATA',
    INIT_LOAD_DATA_ASYNC: 'INIT_LOAD_DATA_ASYNC',
    FEATCH_USER_OK: 'FEATCH_USER_OK',
    FEATCH_DATA_OK: 'FEATCH_DATA_OK',
    CLICK_COUNTRY: 'CLICK_COUNTRY',
    CLICK_COUNTRY_ASYNC: 'CLICK_COUNTRY_ASYNC',
    CLICK_CITY: 'CLICK_CITY',
    CLICK_CITY_ASYNC: 'CLICK_CITY_ASYNC',
    CLICK_IMAGE: 'CLICK_IMAGE',
    CLICK_IMAGE_ASYNC: 'CLICK_IMAGE_ASYNC'
  }
  
  export default actionTypes